DeliveryMan::create([
                    'deliveryman_id' => $this->customerNumber(),
                    'name' => $request->name,
                    'contact' => $request->contact,
                    'email' => $request->email,
                    'tax_number' => $request->tax_number,
                    'password' => Hash::make($request->password),
                    'created_by' => \Auth::user()->creatorId(),
                    'billing_name' => $request->billing_name,
                    'billing_country' => $request->billing_country,
                    'billing_state' => $request->billing_state,
                    'billing_city' => $request->billing_city,
                    'billing_phone' => $request->billing_phone,
                    'billing_zip' => $request->billing_zip,
                    'billing_address' => $request->billing_address,

                    'shipping_name' => $request->shipping_name,
                    'shipping_country' => $request->shipping_country,
                    'shipping_state' => $request->shipping_state,
                    'shipping_city' => $request->shipping_city,
                    'shipping_phone' => $request->shipping_phone,
                    'shipping_zip' => $request->shipping_zip,
                    'shipping_address' => $request->shipping_address,
                    'lang' => !empty($default_language) ? $default_language->value : '',

                ]);